name: Tech RSS Bot

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rss-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run RSS Bot
        env:
          DISCORD_WEBHOOK_URL_TRENDS: ${{ secrets.DISCORD_WEBHOOK_URL_TRENDS }}
          DISCORD_WEBHOOK_URL_SRE: ${{ secrets.DISCORD_WEBHOOK_URL_SRE }}
        run: deno run --allow-net --allow-env --allow-read --allow-write src/bot.ts
